[project]
name = "globant-exercise"
version = "0.1.0"
description = "Globant exercise consuming URL shortener API by is.gd"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "urllib3>=2.4.0",
]
